services:
  db:
    image: mysql:8.0
    container_name: roadreport-db
    environment:
      MYSQL_ROOT_PASSWORD: chipolino123
      MYSQL_DATABASE: roadreport
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./server
    container_name: roadreport-backend
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      FRONTEND_URL: ${FRONTEND_URL}
      BREVO_API_KEY: ${BREVO_API_KEY}
      SENDER_EMAIL: ${SENDER_EMAIL}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./web
    container_name: roadreport-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  db_data: