spring.application.name=RoadReport

spring.datasource.url=jdbc:mysql://localhost:3306/road_report_db
spring.datasource.username= root
spring.datasource.password= bendo2006

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

graphhopper.osm-file=server/data/georgia-260525.osm.pbf
graphhopper.graph-cache=data/graphhopper-cache

application.security.jwt.secret-key= Um9hZFJlcG9ydFNlY3JldEtleTIwMjZDaGlwb2xpbm9zVGVhbSE=
application.security.jwt.expiration = 3600000